from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from PIL import Image
import os
from django.conf import settings
from datetime import datetime


class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()

    def setup_custom_styles(self):
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2C3E50'),
            alignment=TA_CENTER,
            spaceAfter=30
        ))

        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#34495E'),
            spaceAfter=12
        ))

        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=colors.black,
            alignment=TA_LEFT
        ))

    def generate_report(self, detection, output_path):
        """Generate PDF report for a crack detection"""
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )

        story = []

        # Title
        title = Paragraph("Road Crack Detection Report", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 12))

        # Report Info
        report_info = f"""
        <b>Report ID:</b> #{detection.id}<br/>
        <b>Date Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
        <b>Generated By:</b> {detection.user.get_full_name() or detection.user.username}<br/>
        <b>Detection Date:</b> {detection.created_at.strftime('%Y-%m-%d %H:%M:%S')}
        """
        info_para = Paragraph(report_info, self.styles['CustomBody'])
        story.append(info_para)
        story.append(Spacer(1, 20))

        # Images
        if detection.original_image and os.path.exists(detection.original_image.path):
            img = Image.open(detection.original_image.path)
            img_width, img_height = img.size
            aspect = img_height / img_width
            display_width = 3.5 * inch
            display_height = display_width * aspect

            story.append(Paragraph("<b>Original Image</b>", self.styles['CustomHeading']))
            story.append(RLImage(detection.original_image.path, width=display_width, height=display_height))
            story.append(Spacer(1, 12))

        if detection.detected_image and os.path.exists(detection.detected_image.path):
            img = Image.open(detection.detected_image.path)
            img_width, img_height = img.size
            aspect = img_height / img_width
            display_width = 3.5 * inch
            display_height = display_width * aspect

            story.append(Paragraph("<b>Detection Result</b>", self.styles['CustomHeading']))
            story.append(RLImage(detection.detected_image.path, width=display_width, height=display_height))
            story.append(Spacer(1, 12))

        # Detection Results Table
        story.append(Paragraph("<b>Detection Results</b>", self.styles['CustomHeading']))

        results_data = [
            ['Metric', 'Value'],
            ['Crack Count', str(detection.crack_count)],
            ['Crack Type', detection.get_crack_type_display()],
            ['Severity', detection.get_severity_display()],
            ['Confidence Score', f"{detection.confidence_score:.2%}"],
        ]

        results_table = Table(results_data, colWidths=[2 * inch, 3 * inch])
        results_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495E')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))

        story.append(results_table)
        story.append(Spacer(1, 20))

        # Location Information
        if detection.has_location:
            story.append(Paragraph("<b>Location Information</b>", self.styles['CustomHeading']))
            location_text = f"""
            <b>Latitude:</b> {detection.latitude}<br/>
            <b>Longitude:</b> {detection.longitude}<br/>
            <b>Road Name:</b> {detection.road_name or 'Not specified'}<br/>
            <b>Address:</b> {detection.location_address or 'Not specified'}
            """
            location_para = Paragraph(location_text, self.styles['CustomBody'])
            story.append(location_para)
            story.append(Spacer(1, 20))

        # Suggested Maintenance Action
        story.append(Paragraph("<b>Maintenance Recommendation</b>", self.styles['CustomHeading']))
        action_text = f"""
        <b>Suggested Action:</b><br/>
        {detection.get_suggested_action()}<br/><br/>
        <b>Priority Level:</b> {detection.severity}<br/>
        """
        action_para = Paragraph(action_text, self.styles['CustomBody'])
        story.append(action_para)
        story.append(Spacer(1, 20))

        # Additional Notes
        if detection.notes:
            story.append(Paragraph("<b>Additional Notes</b>", self.styles['CustomHeading']))
            notes_para = Paragraph(detection.notes, self.styles['CustomBody'])
            story.append(notes_para)

        # Footer
        story.append(Spacer(1, 30))
        footer_text = """
        <i>This report is auto-generated by Road Crack Detection System. 
        For any queries, please contact your system administrator.</i>
        """
        footer_para = Paragraph(footer_text, self.styles['CustomBody'])
        story.append(footer_para)

        # Build PDF
        doc.build(story)
        return output_path