# Generated by Django 4.2.7 on 2026-04-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crackdetection',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='crack_density_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='estimated_repair_cost',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='inspector_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='maintenance_priority',
            field=models.CharField(blank=True, default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='severity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crackdetection',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detectionreport',
            name='downloaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crackdetection',
            name='crack_type',
            field=models.CharField(choices=[('LONGITUDINAL', 'Longitudinal Crack'), ('TRANSVERSE', 'Transverse Crack'), ('ALLIGATOR', 'Alligator Cracking'), ('BLOCK', 'Block Cracking'), ('UNKNOWN', 'Unknown Type')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='crackdetection',
            name='location_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='crackdetection',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='crackdetection',
            name='road_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='crackdetection',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low - Minor cracks'), ('MEDIUM', 'Medium - Needs monitoring'), ('HIGH', 'High - Immediate repair'), ('SEVERE', 'Severe - Emergency')], default='LOW', max_length=10),
        ),
    ]
